#!/bin/bash -xv
JAVA=java
MAINCLASS=com.sludev.commons.vfs.simpleshell.SimpleShell

CP="/home/kervin/.m2/repository/com/sludev/commons/vfs-simpleshell/0.9/vfs-simpleshell-0.9.jar:\
/home/kervin/.m2/repository/com/sludev/commons/vfs-azure/0.9/vfs-azure-0.9.jar:\
/home/kervin/.m2/repository/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:\
/home/kervin/.m2/repository/org/apache/commons/commons-vfs2/2.0/commons-vfs2-2.0.jar:\
/home/kervin/.m2/repository/org/apache/commons/commons-collections4/4.0/commons-collections4-4.0.jar:\
/home/kervin/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:\
/home/kervin/.m2/repository/org/apache/logging/log4j/log4j-core/2.2/log4j-core-2.2.jar:\
/home/kervin/.m2/repository/org/apache/logging/log4j/log4j-api/2.2/log4j-api-2.2.jar:\
/home/kervin/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.2/log4j-slf4j-impl-2.2.jar:\
/home/kervin/.m2/repository/jline/jline/2.12/jline-2.12.jar:\
/home/kervin/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:\
/home/kervin/.m2/repository/com/microsoft/azure/azure-storage/2.0.0/azure-storage-2.0.0.jar:\
."

$JAVA -cp "$CP" $MAINCLASS

